version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - echo "codebuild is running fimne"
      - pwd
      - ls
      - echo "Packaging application"
      - cd sync-company-status-batch/src && npm run build && cd ..
      - echo "Building application image"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=sync-company-status-batch
      - build_dir=sync-company-status-batch
      - docker build $build_dir -t ${ECR_REPO_NAME}:$IMAGE_TAG --file $build_dir/src/Dockerfile
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_REPO_URL/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Pushing application image to ecr"
      - docker push $ECR_REPO_URL/$ECR_REPO_NAME:$IMAGE_TAG
      - cd sync-company-status-batch/terraform && chmod +x deploy.sh && sh deploy.sh && cd ..
artifacts:
  files:
    - src
