version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - echo "codebuild is running fimne"
      - pwd
      - ls
      - cd src && npm run build
artifacts:
  files:
    - src
