version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
      docker: 18
  pre_build:
    commands:
      - echo "Install dependencies"
      - pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip
      - unzip terraform_0.12.10_linux_amd64.zip
      - mv terraform /bin
      - rm terraform_0.12.10_linux_amd64.zip
      - apt-get update
      - apt-cache search source
      - apt-get install -y curl jq
  build:
    commands:
      - echo "Packaging application"
      - cd snappy-ui/app && npm run build && cd ../..
      - echo "Running terraform validate..."
      - terraform init -backend=false snappy-ui/terraform && terraform validate snappy-ui/terraform
      - cd snappy-ui/terraform && chmod +x deploy.sh && sh deploy.sh && cd ../..
      - aws s3 cp snappy-ui/app/build s3://s3-website-$APPLICATION_ID-$STAGE/snappy/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - snappy-api/terraform/tfplan
  discard-paths: yes
