swagger: "2.0"
info:
  version: "1.0"
  title: "Snappy Search Api"
schemes:
  - https
paths:
  /search/{fieldName}/{fieldValue}:
    get:
      description: "Search by field name and value"
      parameters:
        - name: fieldName
          in: path
          required: true
          type: string
        - name: fieldValue
          in: path
          required: true
          type: string
        - name: from
          in: query
          required: false
          type: integer
          description: "Offset for search results pagination. Default is 0"
        - name: limit
          in: query
          required: false
          type: integer
          description: "Page limit for search results pagination. Default is 100"
      produces:
        - application/json
      responses:
        200:
          description: "Search was successful"
          schema:
            type: array
            items:
              $ref: "#/definitions/SearchResponse"
      x-amazon-apigateway-integration:
        uri: ${search_lambda_arn}
        httpMethod: POST
        type: aws_proxy
  /search:
    options:
      description: "OPTIONS method for Cors"
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: mock
        passthroughBehavior: "when_no_match"
        httpMethod: POST
        default:
          statusCode: "200"
          responseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.test-method-response-header: "'static value'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT'"
            method.response.header.Access-Control-Allow-Origin: "'*'"

definitions:
  SearchResponse:
    type: object
    description: "Search response"
    properties:
      total:
        type: integer
        description: "Total number of matched rows"
      rows:
        type: array
        items:
          $ref: "#/definitions/SearchResultItem"
        description: "Search items"
    required:
      - total

  SearchResultItem:
    type: object
    description: "Individual item in search results"
    properties:
      companyName:
        type: string
    required:
      - companyName
