// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:7b33a77e-1f45-4a0c-9858-c84d622b031c",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_uXKt9LyOO",
    "aws_user_pools_web_client_id": "16rv2s6u2fup7p3u539uagpbd8",
    "oauth": {}
};


export default awsmobile;
